#site information
name: gogo2
description: gogo2 site
author: Bartosz Sobol


# site & jekyll configuration
url: http://gogo2.github.io
baseurl:

encoding: utf-8
timezone: Europe/Warsaw

future: false

sass:
    sass_dir: _scss
    style: expanded

exclude: [
  README.md,
  LICENSE,
  TODO
]