#site information
title: gogo2
description: gogo2 site
author: Bartosz Sobol


url: http://gogo2.github.io
baseurl:

lang: en
encoding: utf-8


# jekyll configuration
timezone: Europe/Warsaw

future: false

sass:
    sass_dir: styles
    style: expanded

exclude: [
  README.md,
  LICENSE,
  TODO
]